#!/usr/bin/env bash

set -e
set -u

# Check if git is available

if ! command -v 'git' >/dev/null 2>&1; then
  echo -n 'Ooops, git not found. '

  if [[ "$(uname)" = 'Darwin' ]]; then
    read -r -p 'Install it (y/n [n])? '

    if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
      echo 'Ok then, nothing much to see here.'
      exit 0
    fi

    if ! command -v 'xcode-select' >/dev/null 2>&1; then
      echo 'Ooops, Xcode not found. '
      read -r -p 'Install it (y/n [n])? '

      if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
        echo 'Ok then, nothing much to see here.'
        exit 0
      fi

      if ! 'xcode-select' --install >/dev/null 2>&1; then
        exit 1
      fi
    fi

  else
    echo -e '\nGo to https://git-scm.com for more info.'
    exit 1
  fi
fi

# Define repo variables

remote_repo='https://github.com/adrfer/bash-oh-my.git'
local_repo="${HOME}/.bash-oh-my"

# Check local repo

if [[ -d "${local_repo}" ]]; then
  echo -n "Backing up ${local_repo}..."
  mv -f "${local_repo%/}"{," copy $(date +%s)"}
  echo ' done.'
fi

# Clone the remote repo into the local repo

echo -n "Cloning repo into ${local_repo}..."

if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
  echo ' done.'
else
  echo 'Ooops, there was an error, try again.'
  exit 1
fi

# Define profile variables

remote_profile="${local_repo}/Misc/Profile"
local_profile="${HOME}/.bash_profile"

# Link local profile

ln -sf "${remote_profile}" "${local_profile}"

echo 'Install successful, enjoy!'
exit 0