#!/usr/bin/env bash

# Check if git is available
if ! command -v 'git' >/dev/null 2>&1; then
  echo 'Ooops, git not found.'
  echo 'Go to https://git-scm.com for more info.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.bash-oh-my"
remote_repo='https://github.com/adrfer/bash-oh-my.git'

# Backup existing files, if any
if [[ -d "${local_repo}" ]]; then
  echo -n 'Backing up existing bash files...'
  mv -f "${local_repo%/}"{," copy $(date +%s)"}
  echo ' done.'
fi

# Download new files
echo -n 'Downloading some bash badassery...'

if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
  echo ' done.'
else
  echo
  echo 'Ooops, there was an error, try again.'
  exit 1
fi

# Setup existing and new files
echo -n 'Setting up your profile...'
ln -sf "${local_repo}/Misc/Profile" "${HOME}/.bash_profile"
echo ' done.'

echo 'All good, enjoy!'
exit 0
