#!/usr/bin/env bash

# Confirm uninstall
read -r -p 'Sure to uninstall (y/n [n])? '

if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
  echo 'Ok then, nothing much to see here.'
  exit 0
fi

# Define repository variables
local_repo="${HOME}/.bash-oh-my"

# Define formatting variables
bold="$(tput bold)"
normal="$(tput sgr0)"

# Remove local repository, if any
if [[ -d "${local_repo}" ]]; then
  echo -n "Removing ${bold}${local_repo}${normal}..."
  rm -rf "${local_repo}"
  echo ' done.'
else
  echo "Local repo ${bold}${local_repo}${normal} not found."
fi

# Define profile variables
local_profile="${HOME}/.bash_profile"
local_readline="${HOME}/.inputrc"

# Remove symlinks, if any
files=( "${local_profile}" "${local_readline}" )

for file in "${files[@]}"; do
  if [[ -L "${file}" ]]; then
    echo -n "Removing ${bold}${file}${normal}..."
    rm -f "${file}"
    echo ' done.'
  else
    echo "Local profile ${bold}${file}${normal} not found."
  fi
done

# Check and restore backup, if any
read -r -p "Check for ${bold}${local_repo}${normal} backups? (y/n [n])? "

if [[ ! "${REPLY}" =~ ^[Yy]$ ]]; then
  echo "Remember to source ${bold}${local_profile}${normal} when available."
  echo 'Ok then, good to go!'
  exit 0
fi

local_repo_backup_pattern='.bash-oh-my copy*'
local_repo_backup=$(find "${HOME}" -maxdepth 1 -type d -name "${local_repo_backup_pattern}" | sort -r | head -n1)

if [[ -n "${local_repo_backup}" ]]; then
  read -r -p "Last backup is ${bold}${local_repo_backup}${normal}. Restore it (y/n [n])? "

  if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
    echo -n "Restoring ${bold}${local_repo_backup}${normal}..."
    mv -f "${local_repo_backup}" "${local_repo}"
    echo ' done.'
  fi
else
  echo "No backups found for ${bold}${local_repo}${normal}."
fi

if [[ ! -L "${local_profile}" ]]; then
  echo "Remember to source ${bold}${local_profile}${normal} when available."
fi

echo 'Uninstall successful, farewell!'
exit 0
