#!/usr/bin/env bash

# Check if git is available
if ! command -v 'git' >/dev/null 2>&1; then
  echo 'Ooops, git not found.'
  echo 'Go to https://git-scm.com for more info.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.bash-oh-my"
remote_repo='https://github.com/adrfer/bash-oh-my.git'

# Update existing files or download new ones
if [[ -d "${local_repo}" ]]; then
  cd "${local_repo}"
  echo -n 'Updating some bash badassery...'

  if git checkout --quiet . >/dev/null 2>&1 && git pull --quiet origin master >/dev/null 2>&1; then
    echo ' done.'
    cd - >/dev/null 2>&1
  else
    echo
    echo 'Ooops, there was an error, try again.'
    exit 1
  fi
else
  echo -n 'Downloading some bash badassery...'

  if git clone --quiet "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
    echo ' done.'
  else
    echo
    echo 'Ooops, there was an error, try again.'
    exit 1
  fi
fi

# Setup existing and new files
echo -n 'Setting up your profile...'
ln -sf "${local_repo}/Misc/Profile" "${HOME}/.bash_profile"
echo ' done.'

echo 'All good, enjoy!'
exit 0
