#!/usr/bin/env bash

# Check if git is available
if ! command -v 'git' >/dev/null; then
  echo 'Ooops, git not found.'
  exit 1
fi

# Define repository variables
local_repo="${HOME}/.bash-oh-my"
remote_repo='https://github.com/adrfer/bash-oh-my.git'

# Update existing files or download new ones
if [[ -d "${local_repo}" ]]; then
  cd "${local_repo}"
  echo -n 'Updating some bash badassery...'

  if git reset --hard >/dev/null 2>&1 && git pull origin master >/dev/null 2>&1; then
    cd - >/dev/null 
    echo ' done.'
  else
    echo
    echo "Ooops, unable to access ${remote_repo}, try again."
    exit 1
  fi
else
  echo -n 'Downloading some bash badassery...'

  if git clone "${remote_repo}" "${local_repo}" >/dev/null 2>&1; then
    echo ' done.'
  else
    echo
    echo "Ooops, unable to access ${remote_repo}, try again."
    exit 1
  fi
fi

# Setup existing and new files
echo -n 'Setting up your profile...'
ln -sf "${local_repo}/Misc/Profile" "${HOME}/.bash_profile"
echo ' done.'

echo 'All good, enjoy!'
exit 0
